dist: xenial
language: php
php:
  - '5.6'

jobs:
  include:
    - language: python
      python: 3.8
      install: pip install -r requirements.txt
      script:
      - cd frontend
      - python -c "print('Hi from Python!')"

    - language: node_js
      node_js: 12
      script:
      - node -e "console.log('Hi from NodeJS!')"
